
package org.example.soapmechanic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PartInvoiceServiceImplService", targetNamespace = "http://soap.mechanic.hccis.ca/", wsdlLocation = "http://localhost:8083/partinvoiceservice?wsdl")
public class PartInvoiceServiceImplService
    extends Service
{

    private final static URL PARTINVOICESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARTINVOICESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PARTINVOICESERVICEIMPLSERVICE_QNAME = new QName("http://soap.mechanic.hccis.ca/", "PartInvoiceServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/partinvoiceservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARTINVOICESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PARTINVOICESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PartInvoiceServiceImplService() {
        super(__getWsdlLocation(), PARTINVOICESERVICEIMPLSERVICE_QNAME);
    }

    public PartInvoiceServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARTINVOICESERVICEIMPLSERVICE_QNAME, features);
    }

    public PartInvoiceServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PARTINVOICESERVICEIMPLSERVICE_QNAME);
    }

    public PartInvoiceServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARTINVOICESERVICEIMPLSERVICE_QNAME, features);
    }

    public PartInvoiceServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartInvoiceServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PartInvoiceService
     */
    @WebEndpoint(name = "PartInvoiceServiceImplPort")
    public PartInvoiceService getPartInvoiceServiceImplPort() {
        return super.getPort(new QName("http://soap.mechanic.hccis.ca/", "PartInvoiceServiceImplPort"), PartInvoiceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartInvoiceService
     */
    @WebEndpoint(name = "PartInvoiceServiceImplPort")
    public PartInvoiceService getPartInvoiceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.mechanic.hccis.ca/", "PartInvoiceServiceImplPort"), PartInvoiceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARTINVOICESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PARTINVOICESERVICEIMPLSERVICE_EXCEPTION;
        }
        return PARTINVOICESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
