
package org.example.soapmechanic;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PartInvoiceService", targetNamespace = "http://soap.mechanic.hccis.ca/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PartInvoiceService {


    /**
     * 
     * @return
     *     returns java.util.List<org.example.soapmechanic.PartInvoice>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInvoices", targetNamespace = "http://soap.mechanic.hccis.ca/", className = "org.example.soapmechanic.GetInvoices")
    @ResponseWrapper(localName = "getInvoicesResponse", targetNamespace = "http://soap.mechanic.hccis.ca/", className = "org.example.soapmechanic.GetInvoicesResponse")
    @Action(input = "http://soap.mechanic.hccis.ca/PartInvoiceService/getInvoicesRequest", output = "http://soap.mechanic.hccis.ca/PartInvoiceService/getInvoicesResponse")
    public List<PartInvoice> getInvoices();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.soapmechanic.PartInvoice
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInvoiceById", targetNamespace = "http://soap.mechanic.hccis.ca/", className = "org.example.soapmechanic.GetInvoiceById")
    @ResponseWrapper(localName = "getInvoiceByIdResponse", targetNamespace = "http://soap.mechanic.hccis.ca/", className = "org.example.soapmechanic.GetInvoiceByIdResponse")
    @Action(input = "http://soap.mechanic.hccis.ca/PartInvoiceService/getInvoiceByIdRequest", output = "http://soap.mechanic.hccis.ca/PartInvoiceService/getInvoiceByIdResponse")
    public PartInvoice getInvoiceById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
